version: "3.9"
services:
  ros-realsense:
    container_name: new-ros-realsense
    image: gsavle/reconcycle:ros-realsense
    network_mode: "host"
    privileged: true
    devices: 
      - "/dev:/dev"
    environment:
      - "ROS_MASTER_URI=http://10.20.0.1:11311"
      - "ROS_IP=10.20.0.2"
      - "DISPLAY=$DISPLAY"
    command: bash -c "roslaunch realsense2_camera rs_camera_and_aruco.launch align_depth:=true enable_sync:=true camera:=realsense_top enable:=false"
    restart: "no"
